import MetricsCard from "../../components/overview/MetricsCard";
import AnalyticsChart from "../../components/overview/AnalyticsChart";
import TopPerformers from "../../components/overview/TopPerformers";
import { AlertTriangle, BadgeEuro, Banknote, Boxes, ClipboardCheck, ShoppingCart } from "lucide-react";

export default function Overview() {
  return <><title>LumiHaus Admin · Overview</title><div className="page-heading"><div><span className="page-kicker">FRIDAY, 04 SEPTEMBER</span><h2>Guten Morgen, Shafin</h2><p>Your German beauty catalog is performing beautifully today.</p></div><button className="button">Download report</button></div><div className="metrics-grid six"><MetricsCard label="Total sales volume" value="৳12.48L" change="+12.5%" icon={<Banknote size={18}/>}/><MetricsCard label="Today's revenue" value="৳84,320" change="+8.2%" icon={<BadgeEuro size={18}/>}/><MetricsCard label="Total orders" value="1,284" change="+6.4%" icon={<ShoppingCart size={18}/>}/><MetricsCard label="Pending bKash" value="8" change="Action needed" icon={<ClipboardCheck size={18}/>}/><MetricsCard label="Active German SKUs" value="428" change="+18 new" icon={<Boxes size={18}/>}/><MetricsCard label="Low stock alerts" value="14" change="-3.1%" icon={<AlertTriangle size={18}/>}/></div><div className="overview-grid"><AnalyticsChart/><OrderDonut/></div><div className="overview-bottom"><TopPerformers/><RecentOrders/></div></>;
}

function OrderDonut(){const parts=[["Delivered",62],["Shipped",14],["Confirmed",12],["Placed",8],["Cancelled",4]];return <section className="card"><div className="section-head"><div><h2>Order status</h2><p>1,284 total orders</p></div></div><div className="donut-wrap"><div className="donut"><div><b>1,284</b><small>Orders</small></div></div><div className="donut-legend">{parts.map(([x,v],i)=><div key={x}><i className={`legend-${i}`}/><span>{x}</span><b>{v}%</b></div>)}</div></div></section>}
function RecentOrders(){return <section className="card"><div className="section-head"><div><h2>Recent orders</h2><p>Latest activity from checkout</p></div><a className="text-button" href="/orders">View all</a></div>{[["#LH-2084","Nusrat Jahan","৳3,450","bKash pending"],["#LH-2083","Sadia Rahman","৳5,200","Confirmed"],["#LH-2082","Tahmid Hasan","৳1,850","Shipped"]].map(x=><div className="recent-order" key={x[0]}><b>{x[0]}</b><span>{x[1]}</span><strong>{x[2]}</strong><em>{x[3]}</em></div>)}</section>}
